# Generated by Django 2.0.2 on 2018-02-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createvmflow', '0001_initial'),
        ('viewflow', '0007_subprocess_subprocesstask'),
        ('subprocessflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubP',
            fields=[
                ('subprocess_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.SubProcess')),
                ('text', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.subprocess',),
        ),
        migrations.CreateModel(
            name='SubT',
            fields=[
                ('subprocesstask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.SubProcessTask')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.subprocesstask',),
        ),
        migrations.RemoveField(
            model_name='subprocess',
            name='process_ptr',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='task_ptr',
        ),
        migrations.DeleteModel(
            name='SubProcess',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
